version: "3.8"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      # - type: bind
      #   source: ./static
      #   target: /opt/app/static
      # - nodeproject:/home/node/app
      - ./app:/home/node/app:cached
    environment:
      - COMPOSE_PROJECT_NAME
    
    command: /bin/sh -c "while sleep 1000; do :; done"

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
<<<<<<< HEAD
      - web-root:/var/www/html
=======
      - project:/var/www/html
>>>>>>> temp
      - ./nginx:/etc/nginx/conf.d
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
    environment:
      - SERVER_NAME
    depends_on:
      - nodejs
    networks:
      - app-network

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - project:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: certonly --webroot --webroot-path=/var/www/html --email sammy@your_domain --agree-tos --no-eff-email --staging -d your_domain  -d www.your_domain

volumes:
  # nodeproject:
  # certbot-etc:
  # certbot-var:
  project:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_PATH_TO_PROJECT} # replace path with your own
      o: bind

networks:
  app-network:
    driver: bridge